/**
 * Emotional Field — deterministic computation from Baseline + Expression Field.
 *
 * This module computes the dynamic pattern layer:
 *   SELF → EXPRESSION → RELATIONSHIP → RETURN → SELF
 *
 * It consumes canonical Baseline and Expression Field objects.
 * It does not re-derive them.
 *
 * The computation is deterministic: identical inputs produce identical outputs.
 * The AI agent uses this structured data to generate sovereign-answer.v2 text,
 * but the field itself is not generated by the model.
 */

import type {
  EmotionalField,
  EmotionalFieldInput,
  PatternObservation,
  ExpressionDynamic,
  RelationalDynamic,
  LoopFeedback,
  CapacityAwareness,
  LoopPhase
} from '@sovereign/agent-contracts';
import { EMOTIONAL_FIELD_VERSION } from '@sovereign/agent-contracts';

/**
 * Build an Emotional Field from canonical Baseline + Expression Field inputs.
 *
 * This is the single canonical computation path.
 * All downstream consumers import from this module.
 */
export function buildEmotionalField(input: EmotionalFieldInput): EmotionalField {
  const self = buildSelfPhase(input);
  const expression = buildExpressionPhase(input);
  const relationship = buildRelationshipPhase(input);
  const returnPhase = buildReturnPhase(input, self, expression, relationship);
  const capacity = buildCapacityPhase(input);

  const allBasisRefs = [
    ...self.flatMap((obs) => obs.basisRefs),
    ...expression.flatMap((dyn) => dyn.basisRefs),
    ...returnPhase.sustainingForces.length ? [] : [],
    ...capacity.openQuestions.length ? [] : []
  ];

  const dominantAxes = input.axes
    .filter((axis) => axis.value >= 55 || axis.state === 'under_pressure' || axis.state === 'gift')
    .map((axis) => axis.id)
    .slice(0, 6);

  const groundingFacets = [...new Set(input.facets.map((f) => f.id))];

  const limitations = [
    'Emotional Field describes observable patterns, not internal psychological states.',
    'What another person is experiencing or intending remains unknown unless confirmed directly.',
    'Pattern observations are grounded in Baseline structure and Expression Field states, not behavioral tracking.',
    'Current conditions may shift expression temporarily; they do not establish permanent traits.',
    'This field supports understanding; it does not predict, diagnose, or prescribe.'
  ];

  return {
    version: EMOTIONAL_FIELD_VERSION,
    generatedAt: new Date().toISOString(),
    subject: input.domain,
    loop: {
      self,
      expression,
      relationship,
      return: returnPhase,
      capacity
    },
    dominantAxes,
    groundingFacets,
    basisRefs: [...new Set(allBasisRefs)],
    provenance: {
      expressionFieldVersion: 'expression-field.v1',
      baselineFacetCount: input.facets.length,
      expressionAxisCount: input.axes.length,
      computationType: 'deterministic'
    },
    limitations
  };
}

// ──────────────────────────────────────────────
// SELF phase: Baseline facets → pattern observations
// ──────────────────────────────────────────────

function buildSelfPhase(input: EmotionalFieldInput): PatternObservation[] {
  return input.facets.map((facet) => ({
    id: `self.${facet.id}`,
    facetId: facet.id,
    observation: facet.description,
    normalExpression: facet.description,
    pressureExpression: facet.shadowExpression,
    capacityExpression: facet.giftExpression,
    basisRefs: [...facet.basisRefs]
  }));
}

// ──────────────────────────────────────────────
// EXPRESSION phase: Expression Field axes → expression dynamics
// ──────────────────────────────────────────────

function buildExpressionPhase(input: EmotionalFieldInput): ExpressionDynamic[] {
  return input.axes.map((axis) => ({
    axisId: axis.id,
    label: axis.label,
    value: axis.value,
    state: axis.state,
    loopContribution: describeLoopContribution(axis),
    pressureResponse: describePressureResponse(axis),
    basisRefs: [...axis.basisRefs]
  }));
}

function describeLoopContribution(axis: { id: string; label: string; value: number; state: string }): string {
  const salience = axis.value >= 70 ? 'highly active' : axis.value >= 55 ? 'active' : axis.value >= 40 ? 'present' : 'quiet';
  const stateLabel = describeStateForLoop(axis.state);
  return `${axis.label} is ${salience} in the expression pattern${stateLabel}.`;
}

function describeStateForLoop(state: string): string {
  switch (state) {
    case 'gift': return ' and is expressing in its flexible, aware form';
    case 'protective': return ' and may be narrowing to protect against perceived risk';
    case 'repressed': return ' and may not have room to express fully';
    case 'overextended': return ' and may be expressing beyond its natural proportion';
    case 'under_pressure': return ' and may be shifting under current conditions';
    case 'integrated': return ' and is expressing in a grounded way';
    case 'mixed': return ' and may be showing more than one quality at once';
    default: return '';
  }
}

function describePressureResponse(axis: { id: string; label: string; state: string }): string {
  switch (axis.state) {
    case 'gift': return `When ${axis.label.toLowerCase()} is under pressure, the same capacity may narrow or overextend before returning to its aware form.`;
    case 'protective': return `Under pressure, ${axis.label.toLowerCase()} may intensify its protective quality, potentially narrowing connection or clarity.`;
    case 'repressed': return `Under pressure, ${axis.label.toLowerCase()} may become harder to access, potentially leaving a gap in the person's available expression.`;
    case 'overextended': return `Under pressure, ${axis.label.toLowerCase()} may push further before reaching its limit, potentially straining nearby capacities.`;
    case 'under_pressure': return `${axis.label} is currently under pressure; the exact form this takes may shift as conditions change.`;
    case 'integrated': return `When pressure rises, ${axis.label.toLowerCase()} may temporarily lose its grounded quality before returning.`;
    case 'mixed': return `Under pressure, the mixed quality of ${axis.label.toLowerCase()} may clarify into a more defined expression or remain fluid.`;
    default: return `The way ${axis.label.toLowerCase()} responds to pressure is still forming and may become clearer with observation.`;
  }
}

// ──────────────────────────────────────────────
// RELATIONSHIP phase: interaction dynamics
// ──────────────────────────────────────────────

function buildRelationshipPhase(input: EmotionalFieldInput): RelationalDynamic {
  if (input.domain === 'self') {
    return buildSelfDomainRelationship(input);
  }
  return buildInteractionDomainRelationship(input);
}

function buildSelfDomainRelationship(input: EmotionalFieldInput): RelationalDynamic {
  const highAxes = input.axes.filter((a) => a.value >= 55);
  const lowAxes = input.axes.filter((a) => a.value < 35);
  const pressureAxes = input.axes.filter((a) => a.state === 'under_pressure' || a.state === 'protective');

  const mechanism = pressureAxes.length > 0
    ? `${pressureAxes.map((a) => a.label).join(' and ')} ${pressureAxes.length === 1 ? 'is' : 'are'} under pressure, which may shape how the person shows up in their own life and decisions.`
    : highAxes.length > 0
      ? `${highAxes.map((a) => a.label).join(' and ')} ${highAxes.length === 1 ? 'is' : 'are'} active, providing a foundation for how the person engages with their circumstances.`
      : 'The pattern is still forming and may become clearer through observation.';

  const manifestation = highAxes.length > 0
    ? `The person's expression is shaped by ${highAxes.map((a) => `${a.label.toLowerCase()} (${a.state})`).join(', ')}.`
    : 'The expression pattern is distributed across multiple qualities without a single dominant axis.';

  const sustaining = pressureAxes.length > 0
    ? pressureAxes.map((a) => `When ${a.label.toLowerCase()} stays under pressure, the pattern may reinforce itself.`)
    : highAxes.length > 0
      ? highAxes.map((a) => `The strength of ${a.label.toLowerCase()} provides a stable foundation.`)
      : ['The pattern is still forming its characteristic shape.'];

  const changing = lowAxes.length > 0
    ? lowAxes.map((a) => `${a.label} is available but underused; giving it more room could shift the pattern.`)
    : pressureAxes.length > 0
      ? pressureAxes.map((a) => `If the pressure on ${a.label.toLowerCase()} eases, the pattern may soften.`)
      : ['Observing the pattern without pressure may reveal natural shifts.'];

  return {
    mechanism,
    manifestation,
    sustainingConditions: sustaining,
    interruptingConditions: changing,
    ownershipDistinction: 'This describes how the person\'s own pattern shows up in their life. What others contribute remains separate and unknown unless confirmed.'
  };
}

function buildInteractionDomainRelationship(input: EmotionalFieldInput): RelationalDynamic {
  const highAxes = input.axes.filter((a) => a.value >= 55);
  const pressureAxes = input.axes.filter((a) => a.state === 'under_pressure' || a.state === 'protective');
  const giftAxes = input.axes.filter((a) => a.state === 'gift');

  const hasPartner = input.interaction?.partnerFacets && input.interaction.partnerFacets.length > 0;
  const hasContacts = input.interaction?.pairContacts && input.interaction.pairContacts.length > 0;

  const mechanism = hasPartner
    ? buildInteractionMechanism(input)
    : hasContacts
      ? `Astrological contacts between participants show ${input.interaction!.pairContacts!.map((c) => `${c.leftBody} ${c.aspect} ${c.rightBody}`).join(', ')}, which may create specific interaction dynamics.`
      : 'Interaction dynamics are inferred from the participant\'s expression patterns and would be enriched by permitted partner context.';

  const manifestation = hasPartner
    ? buildInteractionManifestation(input)
    : 'Without consented partner data, the interaction dynamic is inferred from the available expression pattern alone.';

  const sustaining = giftAxes.length > 0
    ? giftAxes.map((a) => `The gift expression of ${a.label.toLowerCase()} provides a constructive pathway in interaction.`)
    : pressureAxes.length > 0
      ? pressureAxes.map((a) => `When ${a.label.toLowerCase()} is under pressure, the interaction may feel more strained.`)
      : highAxes.length > 0
        ? highAxes.map((a) => `${a.label} provides a stable point of reference in the interaction.`)
        : ['The interaction pattern is still forming.'];

  const changing = pressureAxes.length > 0
    ? pressureAxes.map((a) => `If the pressure on ${a.label.toLowerCase()} shifts, the interaction dynamic may change.`)
    : giftAxes.length > 0
      ? giftAxes.map((a) => `The gift expression of ${a.label.toLowerCase()} is available as a bridge when needed.`)
      : ['The interaction dynamic has room to evolve as observation continues.'];

  return {
    mechanism,
    manifestation,
    sustainingConditions: sustaining,
    interruptingConditions: changing,
    ownershipDistinction: 'Each person owns their own expression, choices, limits, and confirmed experience. The interaction dynamic describes what may form between them, not what either person intends or causes.'
  };
}

function buildInteractionMechanism(input: EmotionalFieldInput): string {
  const partnerFacets = input.interaction!.partnerFacets!;
  const myHighFacets = input.facets.filter((f) => {
    const matchingAxis = input.axes.find((a) => a.facetIds.includes(f.id));
    return matchingAxis && matchingAxis.value >= 55;
  });

  const overlappingFacets = partnerFacets.filter((pf) =>
    myHighFacets.some((mf) => mf.id === pf.id)
  );

  if (overlappingFacets.length > 0) {
    return `Both participants have emphasis in ${overlappingFacets.map((f) => f.title).join(' and ')}, which may create a point of recognition or resonance in the interaction.`;
  }

  const contrastingFacets = partnerFacets.filter((pf) =>
    !myHighFacets.some((mf) => mf.id === pf.id)
  );

  if (contrastingFacets.length > 0) {
    return `The participants emphasize different facets (${contrastingFacets.map((f) => f.title).join(' and ')}), which may create complementary dynamics or points of misunderstanding depending on how they are navigated.`;
  }

  return 'The interaction dynamic is shaped by the participants\' respective expression patterns and the context they share.';
}

function buildInteractionManifestation(input: EmotionalFieldInput): string {
  const axes = input.axes;
  const relationshipAxes = axes.filter((a) => {
    const axisId = a.id;
    return ['anger', 'tenderness', 'trust', 'boundaries', 'repair'].includes(axisId);
  });

  if (relationshipAxes.length === 0) {
    return 'The interaction dynamic is primarily shaped by self-domain qualities expressing through the relationship context.';
  }

  const activeRel = relationshipAxes.filter((a) => a.value >= 55);
  if (activeRel.length > 0) {
    return `In interaction, ${activeRel.map((a) => `${a.label.toLowerCase()} (${a.state})`).join(', ')} ${activeRel.length === 1 ? 'is' : 'are'} particularly active, shaping how connection, limits, and repair show up between people.`;
  }

  return 'The relationship-domain qualities are present but not highly active, suggesting the interaction may be shaped more by self-domain expression than by direct relational dynamics.';
}

// ──────────────────────────────────────────────
// RETURN phase: feedback loop
// ──────────────────────────────────────────────

function buildReturnPhase(
  input: EmotionalFieldInput,
  self: PatternObservation[],
  expression: ExpressionDynamic[],
  relationship: RelationalDynamic
): LoopFeedback {
  const sustainingForces = [
    ...relationship.sustainingConditions,
    ...expression
      .filter((e) => e.state === 'protective' || e.state === 'overextended')
      .map((e) => `The ${e.state} expression of ${e.label.toLowerCase()} may reinforce the current pattern.`)
  ];

  const changingForces = [
    ...relationship.interruptingConditions,
    ...expression
      .filter((e) => e.state === 'gift' || e.state === 'integrated')
      .map((e) => `The ${e.state} expression of ${e.label.toLowerCase()} provides a constructive alternative.`)
  ];

  const giftAxes = expression.filter((e) => e.state === 'gift');
  const pressureAxes = expression.filter((e) => e.state === 'under_pressure' || e.state === 'protective');

  const availableShift = giftAxes.length > 0 && giftAxes[0]
    ? `The gift expression of ${giftAxes[0].label.toLowerCase()} is available as a lower-pressure alternative when the pattern feels stuck.`
    : pressureAxes.length > 0 && pressureAxes[0]
      ? `If the pressure on ${pressureAxes[0].label.toLowerCase()} eases, the pattern may naturally soften.`
      : 'Observing the pattern without pressure may reveal natural points of shift.';

  return {
    sustainingForces: sustainingForces.slice(0, 5),
    changingForces: changingForces.slice(0, 5),
    availableShift
  };
}

// ──────────────────────────────────────────────
// CAPACITY phase: what the person can work with
// ──────────────────────────────────────────────

function buildCapacityPhase(input: EmotionalFieldInput): CapacityAwareness {
  const giftAxes = input.axes.filter((a) => a.state === 'gift');
  const repressedAxes = input.axes.filter((a) => a.state === 'repressed');
  const underusedAxes = input.axes.filter((a) => a.value < 35 && a.state !== 'repressed');
  const pressureAxes = input.axes.filter((a) => a.state === 'under_pressure');

  const availableStrengths = giftAxes.length > 0
    ? giftAxes.map((a) => `${a.label} is expressing in its gift form and can be relied on when needed.`)
    : input.axes
        .filter((a) => a.value >= 55)
        .slice(0, 3)
        .map((a) => `${a.label} is active and available.`);

  const emergingNeeds = [
    ...repressedAxes.map((a) => `${a.label} may need more room to express.`),
    ...pressureAxes.map((a) => `${a.label} is under pressure and may benefit from attention.`)
  ];

  const openQuestions = underusedAxes.length > 0
    ? underusedAxes.slice(0, 3).map((a) => `What would happen if ${a.label.toLowerCase()} had more room?`)
    : ['What the person has directly observed about this pattern.', 'What has been directly confirmed versus inferred.'];

  return {
    availableStrengths: availableStrengths.slice(0, 4),
    emergingNeeds: emergingNeeds.slice(0, 4),
    openQuestions: openQuestions.slice(0, 3)
  };
}
