/**
 * Relationship Field — deterministic computation from two Emotional Fields.
 *
 * This module computes the interaction dynamics layer:
 *   Emotional Field A + Emotional Field B + Pair Contacts
 *          ↓
 *   Relationship Field
 *
 * It consumes canonical Emotional Fields and pair data.
 * It does not re-derive Baseline, Expression Field, or Emotional Field.
 *
 * The computation is deterministic: identical inputs produce identical outputs.
 * The AI agent uses this structured data to generate sovereign-answer.v2 text,
 * but the field itself is not generated by the model.
 */

import type {
  RelationshipField,
  RelationshipFieldInput,
  SharedStructure,
  ContrastingStructure,
  InteractionDynamic,
  RecurringPattern,
  CapacityBetween
} from '@sovereign/agent-contracts';
import { RELATIONSHIP_FIELD_VERSION } from '@sovereign/agent-contracts';

/**
 * Build a Relationship Field from two Emotional Fields and pair data.
 *
 * This is the single canonical computation path.
 * All downstream consumers import from this module.
 */
export function buildRelationshipField(input: RelationshipFieldInput): RelationshipField {
  const sharedStructures = buildSharedStructures(input);
  const contrastingStructures = buildContrastingStructures(input);
  const interactionDynamics = buildInteractionDynamics(input);
  const recurringPatterns = buildRecurringPatterns(input);
  const sustainingForces = buildSustainingForces(input, sharedStructures, interactionDynamics);
  const changingForces = buildChangingForces(input, contrastingStructures, interactionDynamics);
  const availableCapacity = buildAvailableCapacity(input);

  const allBasisRefs = [
    ...sharedStructures.flatMap((s) => s.basisRefs),
    ...contrastingStructures.flatMap((s) => s.basisRefs),
    ...interactionDynamics.flatMap((d) => d.basisRefs),
    ...recurringPatterns.flatMap((p) => p.basisRefs)
  ];

  const dominantInteractionAxes = findDominantInteractionAxes(input);
  const pairContactSummary = input.pairContacts.map((c) => c.display).slice(0, 6);

  const limitations = [
    'Relationship Field describes observable interaction patterns, not internal states or intentions.',
    'What each person is experiencing or intending remains unknown unless confirmed directly.',
    'Pattern observations are grounded in Emotional Field data and pair contacts, not behavioral tracking.',
    'Similarity is not compatibility; contrast is not conflict. Both require direct observation to confirm.',
    'This field supports understanding; it does not predict, diagnose, or prescribe.'
  ];

  return {
    version: RELATIONSHIP_FIELD_VERSION,
    generatedAt: new Date().toISOString(),
    participants: {
      a: { label: input.emotionalFieldA.label, key: input.emotionalFieldA.key },
      b: { label: input.emotionalFieldB.label, key: input.emotionalFieldB.key }
    },
    loop: {
      sharedStructures,
      contrastingStructures,
      interactionDynamics,
      recurringPatterns,
      sustainingForces,
      changingForces,
      availableCapacity
    },
    dominantInteractionAxes,
    pairContactSummary,
    basisRefs: [...new Set(allBasisRefs)],
    provenance: {
      emotionalFieldVersion: input.emotionalFieldA.field.version,
      expressionFieldVersion: input.emotionalFieldA.field.provenance.expressionFieldVersion,
      participantACount: input.emotionalFieldA.field.loop.self.length,
      participantBCount: input.emotionalFieldB.field.loop.self.length,
      pairContactCount: input.pairContacts.length,
      computationType: 'deterministic'
    },
    limitations
  };
}

// ──────────────────────────────────────────────
// SHARED STRUCTURES: where both participants emphasize similar facets
// ──────────────────────────────────────────────

function buildSharedStructures(input: RelationshipFieldInput): SharedStructure[] {
  const results: SharedStructure[] = [];

  for (const pair of input.facetPairs) {
    const axisA = findAxisForFacet(input.emotionalFieldA.field.loop.expression, pair.facetId);
    const axisB = findAxisForFacet(input.emotionalFieldB.field.loop.expression, pair.facetId);

    const aActive = axisA && axisA.value >= 55;
    const bActive = axisB && axisB.value >= 55;

    if (aActive && bActive) {
      results.push({
        facetId: pair.facetId,
        label: pair.participantA.title,
        description: `Both participants have emphasis in ${pair.participantA.title.toLowerCase()}.`,
        interactionDescription: buildSharedInteractionDescription(pair.participantA.title, axisA!, axisB!),
        basisRefs: [...new Set([...pair.participantA.basisRefs, ...pair.participantB.basisRefs])]
      });
    }
  }

  return results;
}

function buildSharedInteractionDescription(
  title: string,
  axisA: { state: string },
  axisB: { state: string }
): string {
  const aState = axisA.state === 'gift' ? 'gift expression' : axisA.state === 'protective' ? 'protective form' : 'active form';
  const bState = axisB.state === 'gift' ? 'gift expression' : axisB.state === 'protective' ? 'protective form' : 'active form';

  if (axisA.state === axisB.state) {
    return `Both participants express ${title.toLowerCase()} in ${aState}, which may create a point of recognition or resonance in the interaction.`;
  }
  return `Participant A expresses ${title.toLowerCase()} in ${aState} while Participant B expresses it in ${bState}, which may create both recognition and points of difference.`;
}

// ──────────────────────────────────────────────
// CONTRASTING STRUCTURES: where participants differ
// ──────────────────────────────────────────────

function buildContrastingStructures(input: RelationshipFieldInput): ContrastingStructure[] {
  const results: ContrastingStructure[] = [];

  for (const pair of input.facetPairs) {
    const axisA = findAxisForFacet(input.emotionalFieldA.field.loop.expression, pair.facetId);
    const axisB = findAxisForFacet(input.emotionalFieldB.field.loop.expression, pair.facetId);

    if (!axisA || !axisB) continue;

    const aValue = axisA.value;
    const bValue = axisB.value;
    const gap = Math.abs(aValue - bValue);

    if (gap >= 20) {
      const aDesc = describeAxisPosition(pair.participantA.title, axisA);
      const bDesc = describeAxisPosition(pair.participantB.title, axisB);
      results.push({
        facetId: pair.facetId,
        label: pair.participantA.title,
        descriptionA: aDesc,
        descriptionB: bDesc,
        interactionDescription: buildContrastInteractionDescription(pair.participantA.title, axisA, axisB),
        basisRefs: [...new Set([...pair.participantA.basisRefs, ...pair.participantB.basisRefs])]
      });
    }
  }

  return results.slice(0, 6);
}

function describeAxisPosition(title: string, axis: { label: string; value: number; state: string }): string {
  const salience = axis.value >= 70 ? 'highly active' : axis.value >= 55 ? 'active' : axis.value >= 40 ? 'present' : 'quieter';
  return `${title} shows ${salience} ${axis.label.toLowerCase()} (${axis.state}).`;
}

function buildContrastInteractionDescription(
  title: string,
  axisA: { value: number },
  axisB: { value: number }
): string {
  if (axisA.value > axisB.value) {
    return `Participant A emphasizes ${title.toLowerCase()} more than Participant B, which may create different expectations or pacing in the interaction.`;
  }
  return `Participant B emphasizes ${title.toLowerCase()} more than Participant A, which may create different expectations or pacing in the interaction.`;
}

// ──────────────────────────────────────────────
// INTERACTION DYNAMICS: how specific axes interact
// ──────────────────────────────────────────────

function buildInteractionDynamics(input: RelationshipFieldInput): InteractionDynamic[] {
  const relationshipAxisIds = ['anger', 'tenderness', 'trust', 'boundaries', 'repair', 'patience'];
  const results: InteractionDynamic[] = [];

  for (const axisId of relationshipAxisIds) {
    const axisA = input.emotionalFieldA.field.loop.expression.find((a) => a.axisId === axisId);
    const axisB = input.emotionalFieldB.field.loop.expression.find((a) => a.axisId === axisId);
    if (!axisA || !axisB) continue;

    const dynamicA = `${axisA.label} is ${describeSalience(axisA.value)} (${axisA.state}).`;
    const dynamicB = `${axisB.label} is ${describeSalience(axisB.value)} (${axisB.state}).`;
    const interactionDescription = buildAxisInteractionDescription(axisA, axisB);

    results.push({
      axisId,
      label: axisA.label,
      dynamicA,
      dynamicB,
      interactionDescription,
      basisRefs: [...new Set([...axisA.basisRefs, ...axisB.basisRefs])]
    });
  }

  return results;
}

function describeSalience(value: number): string {
  if (value >= 70) return 'highly active';
  if (value >= 55) return 'active';
  if (value >= 40) return 'present';
  return 'quieter';
}

function buildAxisInteractionDescription(
  axisA: { label: string; value: number; state: string },
  axisB: { label: string; value: number; state: string }
): string {
  const aHigh = axisA.value >= 55;
  const bHigh = axisB.value >= 55;
  const aPressure = axisA.state === 'under_pressure' || axisA.state === 'protective';
  const bPressure = axisB.state === 'under_pressure' || axisB.state === 'protective';

  if (aHigh && bHigh) {
    return `Both participants have active ${axisA.label.toLowerCase()}, which may create mutual recognition or amplified intensity in this area.`;
  }
  if (aPressure && bPressure) {
    return `Both participants' ${axisA.label.toLowerCase()} is under pressure, which may create a point of shared strain in the interaction.`;
  }
  if (aHigh && !bHigh) {
    return `Participant A's active ${axisA.label.toLowerCase()} meets Participant B's quieter expression, which may create different pacing or expectations.`;
  }
  if (!aHigh && bHigh) {
    return `Participant A's quieter ${axisA.label.toLowerCase()} meets Participant B's active expression, which may create different pacing or expectations.`;
  }
  return `Both participants' ${axisA.label.toLowerCase()} is present but not dominant, leaving room for this quality to develop through interaction.`;
}

// ──────────────────────────────────────────────
// RECURRING PATTERNS: from pair contacts and dominant axes
// ──────────────────────────────────────────────

function buildRecurringPatterns(input: RelationshipFieldInput): RecurringPattern[] {
  const patterns: RecurringPattern[] = [];

  // Pattern from pair contacts
  if (input.pairContacts.length > 0) {
    const contactBasisRefs = input.pairContacts.map((c) => c.id);
    const contactDisplay = input.pairContacts.map((c) => c.display).join(', ');
    patterns.push({
      id: 'pair_contact_pattern',
      description: `Astrological contacts between participants (${contactDisplay}) may create specific recurring dynamics in how they relate.`,
      sustainingConditions: [
        'The contact pattern is grounded in natal positions and remains stable.',
        'Each participant\'s expression of the contacted qualities shapes how the pattern manifests.'
      ],
      interruptingConditions: [
        'Direct observation and communication can clarify whether the pattern is actually operating.',
        'Current conditions may temporarily shift how the contacts express.'
      ],
      basisRefs: contactBasisRefs
    });
  }

  // Pattern from shared dominant axes
  const sharedDominant = findSharedDominantAxes(input);
  if (sharedDominant.length > 0) {
    const axisLabels = sharedDominant.map((a) => a.label);
    patterns.push({
      id: 'shared_expression_pattern',
      description: `Both participants have active expression in ${axisLabels.join(', ')}, which may create recurring dynamics around these qualities.`,
      sustainingConditions: [
        `The shared emphasis on ${axisLabels[0]?.toLowerCase() ?? 'these qualities'} provides a common reference point.`,
        'When both participants are in their gift expression, the shared quality may become a strength.'
      ],
      interruptingConditions: [
        `If one participant's ${axisLabels[0]?.toLowerCase() ?? 'expression'} shifts under pressure, the shared dynamic may change.`,
        'Observing the pattern without pressure may reveal natural variations.'
      ],
      basisRefs: sharedDominant.flatMap((a) => a.basisRefs)
    });
  }

  // Pattern from contrasting dominant axes
  const contrastingDominant = findContrastingDominantAxes(input);
  if (contrastingDominant.length > 0) {
    const axisLabels = contrastingDominant.map((a) => a.label);
    patterns.push({
      id: 'contrasting_expression_pattern',
      description: `Participants emphasize different expression qualities (${axisLabels.join(', ')}), which may create complementary dynamics or points of misunderstanding.`,
      sustainingConditions: [
        'The contrast provides different perspectives and capabilities.',
        'When each participant respects the other\'s different emphasis, the contrast can be a source of growth.'
      ],
      interruptingConditions: [
        'If the contrast is experienced as deficiency rather than difference, it may create friction.',
        'Direct conversation about different styles can transform contrast into complementary strength.'
      ],
      basisRefs: contrastingDominant.flatMap((a) => a.basisRefs)
    });
  }

  return patterns;
}

// ──────────────────────────────────────────────
// SUSTAINING FORCES: what keeps the interaction pattern in place
// ──────────────────────────────────────────────

function buildSustainingForces(
  input: RelationshipFieldInput,
  shared: SharedStructure[],
  dynamics: InteractionDynamic[]
): string[] {
  const forces: string[] = [];

  if (shared.length > 0) {
    forces.push(`Shared emphasis in ${shared.map((s) => s.label.toLowerCase()).join(', ')} provides a stable foundation for the interaction.`);
  }

  const highContactAxes = input.pairContacts
    .filter((c) => c.display.includes('☌') || c.display.includes('△'))
    .map((c) => c.display);
  if (highContactAxes.length > 0) {
    forces.push(`Strong astrological contacts (${highContactAxes.join(', ')}) may reinforce certain interaction dynamics.`);
  }

  const giftDynamics = dynamics.filter((d) => {
    const aState = input.emotionalFieldA.field.loop.expression.find((e) => e.axisId === d.axisId)?.state;
    const bState = input.emotionalFieldB.field.loop.expression.find((e) => e.axisId === d.axisId)?.state;
    return aState === 'gift' || bState === 'gift';
  });
  if (giftDynamics.length > 0) {
    forces.push(`Gift expression in ${giftDynamics.map((d) => d.label.toLowerCase()).join(', ')} provides constructive pathways in the interaction.`);
  }

  return forces.slice(0, 5);
}

// ──────────────────────────────────────────────
// CHANGING FORCES: what could shift the pattern
// ──────────────────────────────────────────────

function buildChangingForces(
  input: RelationshipFieldInput,
  contrasting: ContrastingStructure[],
  dynamics: InteractionDynamic[]
): string[] {
  const forces: string[] = [];

  if (contrasting.length > 0) {
    forces.push(`Different emphasis in ${contrasting.map((s) => s.label.toLowerCase()).join(', ')} provides room for the interaction to evolve.`);
  }

  const pressureDynamics = dynamics.filter((d) => {
    const aState = input.emotionalFieldA.field.loop.expression.find((e) => e.axisId === d.axisId)?.state;
    const bState = input.emotionalFieldB.field.loop.expression.find((e) => e.axisId === d.axisId)?.state;
    return aState === 'under_pressure' || bState === 'under_pressure' || aState === 'protective' || bState === 'protective';
  });
  if (pressureDynamics.length > 0) {
    forces.push(`If pressure on ${pressureDynamics.map((d) => d.label.toLowerCase()).join(', ')} eases, the interaction dynamic may naturally shift.`);
  }

  forces.push('Direct observation and communication about what each person is actually experiencing can redirect the pattern.');

  return forces.slice(0, 5);
}

// ──────────────────────────────────────────────
// AVAILABLE CAPACITY: what the pair has to work with
// ──────────────────────────────────────────────

function buildAvailableCapacity(input: RelationshipFieldInput): CapacityBetween {
  const aStrengths = input.emotionalFieldA.field.loop.capacity.availableStrengths;
  const bStrengths = input.emotionalFieldB.field.loop.capacity.availableStrengths;
  const sharedAxes = findSharedDominantAxes(input);

  const availableStrengths = [
    ...sharedAxes.slice(0, 2).map((a) => `Shared ${a.label.toLowerCase()} provides a common strength.`),
    ...aStrengths.slice(0, 1).map((s) => `Participant A brings: ${s}`),
    ...bStrengths.slice(0, 1).map((s) => `Participant B brings: ${s}`)
  ];

  const aNeeds = input.emotionalFieldA.field.loop.capacity.emergingNeeds;
  const bNeeds = input.emotionalFieldB.field.loop.capacity.emergingNeeds;
  const emergingNeeds = [
    ...aNeeds.slice(0, 1).map((n) => `Participant A: ${n}`),
    ...bNeeds.slice(0, 1).map((n) => `Participant B: ${n}`)
  ];

  const openQuestions = [
    'What each person has directly observed about how they interact.',
    'What has been directly confirmed versus assumed about the dynamic.',
    'What each person needs from the interaction that has not yet been expressed.'
  ];

  return {
    availableStrengths: availableStrengths.slice(0, 4),
    emergingNeeds: emergingNeeds.slice(0, 4),
    openQuestions
  };
}

// ──────────────────────────────────────────────
// HELPERS
// ──────────────────────────────────────────────

/**
 * Lightweight axis snapshot for comparison purposes.
 * Matches the subset of ExpressionAxisValue fields used by Relationship Field.
 */
interface AxisSnapshot {
  id: string;
  label: string;
  value: number;
  state: string;
  basisRefs: string[];
}

function findAxisForFacet(
  expression: import('@sovereign/agent-contracts').ExpressionDynamic[],
  facetId: string
): AxisSnapshot | undefined {
  for (const dyn of expression) {
    if (dyn.basisRefs.some((ref) => ref.includes(facetId) || ref === facetId)) {
      return {
        id: dyn.axisId,
        label: dyn.label,
        value: dyn.value,
        state: dyn.state,
        basisRefs: dyn.basisRefs
      };
    }
  }
  return undefined;
}

function findDominantInteractionAxes(input: RelationshipFieldInput): string[] {
  const relationshipAxisIds = new Set(['anger', 'tenderness', 'trust', 'boundaries', 'repair', 'patience']);
  const axes = new Map<string, number>();

  for (const dyn of input.emotionalFieldA.field.loop.expression) {
    if (relationshipAxisIds.has(dyn.axisId)) {
      axes.set(dyn.axisId, (axes.get(dyn.axisId) ?? 0) + dyn.value);
    }
  }
  for (const dyn of input.emotionalFieldB.field.loop.expression) {
    if (relationshipAxisIds.has(dyn.axisId)) {
      axes.set(dyn.axisId, (axes.get(dyn.axisId) ?? 0) + dyn.value);
    }
  }

  return [...axes.entries()]
    .filter(([, total]) => total >= 100)
    .sort((a, b) => b[1] - a[1])
    .map(([id]) => id)
    .slice(0, 4);
}

function findSharedDominantAxes(input: RelationshipFieldInput): Array<{ id: string; label: string; basisRefs: string[] }> {
  const results: Array<{ id: string; label: string; basisRefs: string[] }> = [];

  for (const dynA of input.emotionalFieldA.field.loop.expression) {
    if (dynA.value < 55) continue;
    const dynB = input.emotionalFieldB.field.loop.expression.find((b) => b.axisId === dynA.axisId);
    if (!dynB || dynB.value < 55) continue;

    results.push({
      id: dynA.axisId,
      label: dynA.label,
      basisRefs: [...new Set([...dynA.basisRefs, ...dynB.basisRefs])]
    });
  }

  return results;
}

function findContrastingDominantAxes(input: RelationshipFieldInput): Array<{ id: string; label: string; basisRefs: string[] }> {
  const results: Array<{ id: string; label: string; basisRefs: string[] }> = [];

  for (const dynA of input.emotionalFieldA.field.loop.expression) {
    const dynB = input.emotionalFieldB.field.loop.expression.find((b) => b.axisId === dynA.axisId);
    if (!dynB) continue;

    const gap = Math.abs(dynA.value - dynB.value);
    if (gap < 20) continue;

    const oneActive = dynA.value >= 55 || dynB.value >= 55;
    if (!oneActive) continue;

    results.push({
      id: dynA.axisId,
      label: dynA.label,
      basisRefs: [...new Set([...dynA.basisRefs, ...dynB.basisRefs])]
    });
  }

  return results;
}
